### ISSUE TITLE
Light rendering

### ISSUE THREAD

**Issue by ostwilkens** [mrk-its/bevy_webgl2#7]
_First off, a huge thanks to @mrk-its for the work on this plugin. I can see a ton of use of this in the future. I will be testing bevy_webgl2 in a project of mine and reporting back when I encounter issues, contributing where I am able._ 

Light sources are not behaving as expected. They distort colors, and under some circumstances even make a surface darker. 
I assume this is known and a work-in-progress, but we can track the progress here. 

_bevy 0.3.0 `3d_scene` example_
![bevy_windows](https://user-images.githubusercontent.com/5286600/99703899-f4c65900-2a97-11eb-901e-82a84e8a133f.jpg)

_bevy_webgl2 `3d_scene` example_
![bevy_webgl2](https://user-images.githubusercontent.com/5286600/99703896-f42dc280-2a97-11eb-8d9f-1f649c675989.jpg)

**Comment by mrk-its** [comment]
What browser (including exact version), operating system and GPU you are using? Please also include git sha1 of bevy_webgl2 you are using. This is important because this example renders correctly for me (I had identical rendering bug, but it was fixed some time ago). Are you using freshest version of bevy_webgl2 now?

**Comment by ostwilkens** [comment]
Sorry about this; I just realized I haven't kept bevy_webgl2 up-to-date, while still referencing the latest git version of bevy_webgl2. The change to AmbientColor trigged this. 
Closing!
